version: '3.7'

services:
  pgdb:
    image: postgres:13-alpine
    env_file:
      - .env.example
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - portaler
  rediscache:
    image: bitnami/redis:6.0
    env_file:
      - .env.example
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - portaler
  discord_bot:
    image: aut1sto/portaler-bot:beta
    env_file:
      - .env.example
    restart: unless-stopped
    environment:
      - API_URL=https://api_server/
    depends_on:
      - pgdb
      - rediscache
    networks:
      - portaler
  api_server:
    image: aut1sto/portaler:beta
    env_file:
      - .env.example
    restart: unless-stopped
    ports:
      - '7777:4242'
    depends_on:
      - pgdb
      - rediscache
    networks:
      - portaler
  bin_etl:
    image: aut1sto/portaler-etl:beta
    env_file:
      - .env.example
    restart: unless-stopped
    depends_on:
      - pgdb
      - rediscache
      - api_server
    networks:
      - portaler

networks:
  portaler:
    driver: 'bridge'

volumes:
  db_data: {}
